### ISSUE TITLE
Program can not terminate without closing console window.

### ISSUE THREAD

**Issue by amritabithi** [Pymmdrza/SoloMinerV2#6]
When I try to terminate the script using "Control+C" I am unable to exit the program, which will stay in the shutdown phase indefinitely.  A copy of the output I see is below:

```
[ 12:11:02.655562 ]  [*] Bitcoin Miner Thread Started
 --------------~~(   M M D R Z A . C o M   )~~--------------
Traceback (most recent call last):
  File "SoloMinerV2.py", line 248, in thread_bitcoin_miner
    ret = bitcoin_miner(self)
  File "SoloMinerV2.py", line 108, in bitcoin_miner
    target = (ctx.nbits[2 :] + '00' * (int(ctx.nbits[:2] , 16) - 3)).zfill(64)
TypeError: 'NoneType' object is not subscriptable
^C [ 12:11:04.462354 ]  Terminating Miner, Please Wait..
^C [ 12:11:04.684402 ]  Terminating Miner, Please Wait..
^C [ 12:11:04.847707 ]  Terminating Miner, Please Wait..
^C [ 12:11:05.284101 ]  Terminating Miner, Please Wait..
^C [ 12:11:05.477145 ]  Terminating Miner, Please Wait..
^C [ 12:11:05.679349 ]  Terminating Miner, Please Wait..
```

**Comment by amritabithi** [comment]
As I was submitting this issue the program finally did end after timingout to ckpool, so I will check my firewall and see if maybe the connection is being blocked causing the "non subscriptable" error also...

```
C [ 12:11:19.753644 ]  Terminating Miner, Please Wait..
^C [ 12:11:19.947303 ]  Terminating Miner, Please Wait..
^C [ 12:11:20.452499 ]  Terminating Miner, Please Wait..
^C [ 12:11:20.778745 ]  Terminating Miner, Please Wait..
^C [ 12:11:21.090920 ]  Terminating Miner, Please Wait..
^C [ 12:11:21.403465 ]  Terminating Miner, Please Wait..
 [ 12:13:09.286708 ]  [*] Subscribe thread()
Traceback (most recent call last):
  File "SoloMinerV2.py", line 272, in thread_new_block
    ret = block_listener(self)
  File "SoloMinerV2.py", line 201, in block_listener
    sock.connect(('solo.ckpool.org' , 3333))
TimeoutError: [Errno 110] Connection timed out

```
